"""empty message

Revision ID: 5a1b4ad411bd
Revises: 9b651f4015c6
Create Date: 2023-06-03 15:04:14.623486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1b4ad411bd'
down_revision = '9b651f4015c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('_question_answer_uc', ['name', 'phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('_question_answer_uc', type_='unique')

    # ### end Alembic commands ###
