"""empty message

Revision ID: 9b651f4015c6
Revises: c7940701f4af
Create Date: 2022-11-29 10:51:27.782634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b651f4015c6'
down_revision = 'c7940701f4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.drop_column('passwort_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwort_hash', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
